### ISSUE TITLE
Frezze

### ISSUE THREAD

**Issue by kalifuzzifa** [jhalon/PortForce#2]
Hi There, 

was just trying out your portforce script and everytime i executed it just froze on the first line.
I an noob in this field sorry if its just something basic if i am missing.
![Screenshot 2021-01-14 14:20:52](https://user-images.githubusercontent.com/76675978/104566576-c74ef380-5673-11eb-844c-bc4e4d9d9a10.png)

**Comment by jhalon** [comment]
Hello,

If you look at lines 161 and 174 you'll see an `endswith` method being used. I'm assuming it's freezing because the script can't find the "Enter login" text and this it hangs. Since those are hardcoded, you'll usually have to modify the script so that match the login/password prompts.

Cheers!

**Comment by kalifuzzifa** [comment]
Hello,

Thank you for the reply, will try modifying as per my requirement.

thanks once again! :)
